// 유저, 혹은 팀원의 직군, 직접 추가 가능
export const UserRoles = [
  'Frontend',
  'Backend',
  'Full Stack',
  'iOS',
  'Android',
  'Desktop',
  '기획자',
  'PM',
  'Designer',
] as const;

// 프로젝트 카테고리, 직접 추가 불가
export const ProjectCategories = {
  FINANCE: { code: 1, name: '금융' },
  HEALTHCARE: { code: 2, name: '헬스케어' },
  EDUCATION: { code: 3, name: '교육' },
  COMMERCE: { code: 4, name: '커머스' },
  TRAVEL: { code: 5, name: '여행' },
  ENTERTAINMENT: { code: 6, name: '엔터테인먼트' },
  PRODUCTIVITY: { code: 7, name: '생산성' },
  OTHER: { code: 8, name: '기타' },
} as const;

// 기술 스택 리스트, 직접 추가 가능
export const TechStacks = [
  'Python',
  'Spring Framework',
  'AWS',
  'Git',
  'iOS',
  'Android',
  'HTML/CSS',
  'JavaScript',
  'Java',
  'Linux',
  'Kotlin',
  'Swift',
  'C',
  'C++',
  'PHP',
  'Docker',
  'React',
  'GitHub',
  'JPA',
  'DevOps',
  'R',
  'Figma',
  'Adobe PhotoShop',
  'Adobe XD',
  'Adobe Illustrator',
  'Sketch',
  'Protopie',
  'Node.js',
  'JSP',
  'Vue.js',
  'Bootstrap',
  'Ruby',
  'Hadoop',
  'SQL',
  'NoSQL',
  'GitLab',
  'TypeScript',
  'GraphQL',
  'Kubernetes',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Django',
  'Flask',
  'Express.js',
  'ASP.NET',
  'Ruby on Rails',
  'Go',
  'Rust',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'Oracle',
  'Redis',
  'Google Cloud Platform',
  'Microsoft Azure',
  'Heroku',
  'React Native',
  'Flutter',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Scikit-learn',
  'Jest',
  'Selenium',
  'Cypress',
  'Jenkins',
  'Travis CI',
  'CircleCI',
  'Elasticsearch',
  'RabbitMQ',
  'Kafka',
  'WebAssembly',
  'Sass/SCSS',
  'Ansible',
  'Terraform',
  'Zeplin',
  'InVision',
  'Blender',
  'Unity',
  'Unreal Engine',
  'Scala',
  'Dart',
  'Puppet',
  'Chef',
  'Prometheus',
  'Grafana',
  'Tableau',
  'Power BI',
  'Airflow',
  'Spark',
  'Cassandra',
  'Neo4j',
  'Mathematica',
  'MATLAB',
  'SolidWorks',
  'AutoCAD',
  'Fusion 360',
  'Affinity Designer',
  'Framer',
  'Webflow',
  'Magento',
  'Shopify',
  'Wordpress',
] as const;
