import '../styles/globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import GlobalFooter from './layout/footer/GlobalFooter';
import GlobalHeader from './layout/header/GlobalHeader';
import ModalPortal from './layout/modal/ModalPotal';
import ReactQueryProviders from '@/hooks/useReactQuery';
import { cn } from '@/lib/utils';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'PRism',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className={cn(pretendard.variable, 'bg-gray-50')}>
        <ReactQueryProviders>
          <GlobalHeader />
          {children}
          <GlobalFooter />
          <ModalPortal />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
